In [20]:
import pandas as pd
def clear_dates(df):
    df['Text'] = df['Title'] + " " + df['Article'] + " " + df['Tags']
    df = df.drop(columns=['Title', 'Article', 'Tags'])
    df = df[df['Text'].notnull()]
    isnull = df['Date'].isnull()
    for i in range(1, df.shape[0]):
        if isnull.iloc[i]:
            df['Date'].iloc[i] = df['Date'].iloc[i - 1]
    df['Date'] = pd.to_datetime(df['Date'])
    df = df.drop_duplicates(['Text'])
    return df

In [4]:
def delete_words(df):
    marks = ['!', '\"', "\'", '\(', '\)', '\-', '\+', ',', '\.', ';', ':', '<', '>', '\[', '\]', '%', '\$']
    for m in marks:
        df['Text'] = df['Text'].replace(m, " ", regex=True)
    numbers = [str(i) for i in range(10)]
    for n in numbers:
        df['Text'] = df['Text'].replace(n, " ", regex=True)
    df['Text'] = df['Text'].str.lower()
    aux_words = [
        'даже',
        "еще",
        "именно",
        "как раз",
        "только",
        "просто",
        "прямо",
        "буквально",
        "хоть",
        "хотя бы",
        "почти",
        "чуть не",
        "чуть ли не",
        "едва ли",
        "все таки",
        "все же",
        "но",
        "да",
        "или",
        "то есть",
        "именно",
        "как то",
        "будь то",
        "то",
        "не",
        "ли",
        "как и",
        "чем",
        "тем",
        "словно",
        "точно",
        "в целом",
        "в общем",
        "в основном",
        "во многом",
        "во",
        "без малого",
        "в итоге",
        "в результате",
        "к слову",
        "в идеале",
        "в частности",
        "что",
        "а вдобавок",
        "а именно",
        "а также",
        "а то",
        "будто",
        "вдобавок",
        "даже",
        "же",
        "едва",
        "ежели",
        "если",
        "зато",
        "зачем",
        "или",
        "как",
        "когда",
        "коли",
        "из",
        "однако",
        "пока",
        "потому",
        "пусть",
        "также",
        "тоже",
        "хотя",
        "точно",
        "чем",
        "чтобы",
        "без",
        "близ",
        "во",
        "вместо",
        "вне",
        "для",
        "до",
        "за",
        "из",
        "из за",
        "из под",
        "кроме",
        "между",
        "на",
        "над",
        "об",
        "от",
        "перед",
        "по",
        "под",
        "при",
        "про",
        "ради",
        "со",
        "сквозь",
        "среди",
        "через",
        "здесь"
    ]
    for w in aux_words:
        df['Text'] = df['Text'].replace(" " + w + " ", " ", regex=True)
        df['Text'] = df['Text'].replace("^" + w + " ", " ", regex=True)
        df['Text'] = df['Text'].replace(" " + w + "$", " ", regex=True)
    letters = list(map(chr, range(ord('а'), ord('я')+1)))
    for l in letters:
        df['Text'] = df['Text'].replace(" " + l + " ", " ", regex=True)
        df['Text'] = df['Text'].replace("^" + l + " ", " ", regex=True)
        df['Text'] = df['Text'].replace(" " + l + "$", " ", regex=True)
    return df

In [5]:
import re

class Porter:
    PERFECTIVEGROUND =  re.compile(u"((ив|ивши|ившись|ыв|ывши|ывшись)|((?<=[ая])(в|вши|вшись)))$")
    REFLEXIVE = re.compile(u"(с[яь])$")
    ADJECTIVE = re.compile(u"(ее|ие|ые|ое|ими|ыми|ей|ий|ый|ой|ем|им|ым|ом|его|ого|ему|ому|их|ых|ую|юю|ая|яя|ою|ею)$")
    PARTICIPLE = re.compile(u"((ивш|ывш|ующ)|((?<=[ая])(ем|нн|вш|ющ|щ)))$")
    VERB = re.compile(u"((ила|ыла|ена|ейте|уйте|ите|или|ыли|ей|уй|ил|ыл|им|ым|ен|ило|ыло|ено|ят|ует|уют|ит|ыт|ены|ить|ыть|ишь|ую|ю)|((?<=[ая])(ла|на|ете|йте|ли|й|л|ем|н|ло|но|ет|ют|ны|ть|ешь|нно)))$")
    NOUN = re.compile(u"(а|ев|ов|ие|ье|е|иями|ями|ами|еи|ии|и|ией|ей|ой|ий|й|иям|ям|ием|ем|ам|ом|о|у|ах|иях|ях|ы|ь|ию|ью|ю|ия|ья|я)$")
    RVRE = re.compile(u"^(.*?[аеиоуыэюя])(.*)$")
    DERIVATIONAL = re.compile(u".*[^аеиоуыэюя]+[аеиоуыэюя].*ость?$")
    DER = re.compile(u"ость?$")
    SUPERLATIVE = re.compile(u"(ейше|ейш)$")
    I = re.compile(u"и$")
    P = re.compile(u"ь$")
    NN = re.compile(u"нн$")

    def stem(word):
        word = word.lower()
        word = word.replace(u'ё', u'е')
        m = re.match(Porter.RVRE, word)
        if m is None:
            return word
        if m.groups():
            pre = m.group(1)
            rv = m.group(2)
            temp = Porter.PERFECTIVEGROUND.sub('', rv, 1)
            if temp == rv:
                rv = Porter.REFLEXIVE.sub('', rv, 1)
                temp = Porter.ADJECTIVE.sub('', rv, 1)
                if temp != rv:
                    rv = temp
                    rv = Porter.PARTICIPLE.sub('', rv, 1)
                else:
                    temp = Porter.VERB.sub('', rv, 1)
                    if temp == rv:
                        rv = Porter.NOUN.sub('', rv, 1)
                    else:
                        rv = temp
            else:
                rv = temp
            
            rv = Porter.I.sub('', rv, 1)

            if re.match(Porter.DERIVATIONAL, rv):
                rv = Porter.DER.sub('', rv, 1)

            temp = Porter.P.sub('', rv, 1)
            if temp == rv:
                rv = Porter.SUPERLATIVE.sub('', rv, 1)
                rv = Porter.NN.sub(u'н', rv, 1)
            else:
                rv = temp
            word = pre+rv
        return word
    stem=staticmethod(stem)

In [6]:
def stemming(s):
    s = s.split()
    s = map(lambda ss: Porter.stem(ss), s)
    return " ".join(s)
def stem(df):
    for i in range(df.shape[0]):
        df['Text'].iloc[i] = stemming(df['Text'].iloc[i])
    return df

In [23]:
import datetime
def preprocess(df):
    df = clear_dates(df)
    df = delete_words(df)
    df = stem(df)
    df = df[df['Date'] >= datetime.datetime(2015, 1, 1)]
    return df

In [8]:
df = pd.read_csv("./interfax.csv", parse_dates=True)
interfax = preprocess(df)
interfax.head(10)

C:\Users\Egor Kolyuzhnov\AppData\Local\Temp\ipykernel_18428\540580304.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'].iloc[i] = df['Date'].iloc[i - 1]
C:\Users\Egor Kolyuzhnov\AppData\Local\Temp\ipykernel_18428\1043547710.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Text'].iloc[i] = stemming(df['Text'].iloc[i])

,Unnamed: 0,Date,Text
0,0,2023-04-09 12:16:00,марсел пят человек пострада обрушен жил дом мо...
1,1,2023-04-09 11:33:00,песк назва неадекватн реакц запад план рф пост...
2,2,2023-04-09 11:21:00,воен рф созда спецгрупп борьб западн танк моск...
3,3,2023-04-09 11:02:00,полиц ира будет отслежива ношен хиджаб помощ к...
4,4,2023-04-09 11:22:00,воен рф созда спецгрупп борьб западн танк моск...
5,5,2023-04-09 06:08:00,сша направ подводн лодк красн мор напряжен отн...
6,6,2023-04-09 08:33:00,случ эт ноч воскресен апрел обстрел израил сир...
7,7,2023-04-09 00:09:00,православн отмеча вербн воскресен москв апрел ...
8,8,2023-04-09 04:44:00,три ракет был выпущ сир сторон голанск высот а...
9,9,2023-04-08 21:47:00,динам спартак сыгра внич матч рпл собол заб св...

In [24]:
df = pd.read_csv("./ria.csv", parse_dates=True)
ria = preprocess(df)
ria

C:\Users\Egor Kolyuzhnov\AppData\Local\Temp\ipykernel_18428\1979864951.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("./ria.csv", parse_dates=True)
C:\Users\Egor Kolyuzhnov\AppData\Local\Temp\ipykernel_18428\1043547710.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Text'].iloc[i] = stemming(df['Text'].iloc[i])

,Unnamed: 0,Date,Text
0,0,2023-04-10,российск авиац солнцепек нанесл удар украинск ...
1,1,2023-04-10,врач госпитал вишневск спасл бойц вытащ пул ег...
2,2,2023-04-10,российск пво нача сво уничтож бол украинск бай...
3,3,2023-04-09,трамп указа трет миров войн сво обращен соцсет...
4,4,2023-04-09,спецоперац апрел ки брос артемовск элитн войск...
...,...,...,...
106012,106012,2017-12-11,путин приказа нача вывод российск группировк с...
106717,106717,2017-12-05,учен назва признак скор смерт * учен * давлен ...
107273,107273,2017-11-30,футболист зенит терент пострада бытов драк сан...
107573,107573,2017-11-27,созда устройств борьб зависим смартфон * смарт...
109568,109568,2017-10-26,федор емельяненк назва брат александр иуд приз...

In [30]:
df = pd.read_csv("./rbc.csv", parse_dates=True)
df

,Unnamed: 0,URL,Title,Article,Tags,Date
0,0,NaN,NaN,Главные новости РБК в прямом эфире. На канале ...,[],NaN
1,1,NaN,NaN,Существует ли безопасная доля алкоголя? Ученые...,[],NaN
2,2,https://pro.rbc.ru/news/642ec7ee9a79475492013b...,Какая доза алкоголя безопасна для здоровья,"Одни ученые говорят о том, что безопасной дозы...",[],NaN
3,3,NaN,NaN,Внедорожник Tank 500 стал доступен для покупки...,[],NaN
4,4,https://www.autonews.ru/news/643691b89a7947a97...,Tank объявил о начале продаж флагманского внед...,Фото: Tank В России стартовали продажи рамного...,['\n Новости\n ...,NaN
...,...,...,...,...,...,...
139666,139666,NaN,NaN,Разработчик Flappy Bird удалит игру из магазин...,[],NaN
139667,139667,NaN,NaN,У России - первая олимпийская медаль! Поздравл...,[],NaN
139668,139668,NaN,NaN,В Омске выпал снег черного цвета http://top.rb...,[],NaN
139669,139669,NaN,NaN,Эксперты оценили золотые медали Олимпиады в 55...,[],NaN
139670,139670,NaN,NaN,"Австриец Маттиас Майер выиграл ""золото"" в скор...",[],NaN

In [55]:
import math

def parse_date(url):
    if (not isinstance(url, str) and math.isnan(url)):
        return None
    date = re.findall("[0-9]+/", url)
    if len(date) != 3:
        return None
    
    year = int(date[2][:-1])
    month = int(date[1][:-1])
    day = int(date[0][:-1])
    try:
        return datetime.datetime(year, month, day)
    except:
        return None
for i in range(df.shape[0]):
    df["Date"].iloc[i] = parse_date(df["URL"].iloc[i])

,Unnamed: 0,URL,Title,Article,Tags,Date
0,0,NaN,NaN,Главные новости РБК в прямом эфире. На канале ...,[],None
1,1,NaN,NaN,Существует ли безопасная доля алкоголя? Ученые...,[],None
2,2,https://pro.rbc.ru/news/642ec7ee9a79475492013b...,Какая доза алкоголя безопасна для здоровья,"Одни ученые говорят о том, что безопасной дозы...",[],None
3,3,NaN,NaN,Внедорожник Tank 500 стал доступен для покупки...,[],None
4,4,https://www.autonews.ru/news/643691b89a7947a97...,Tank объявил о начале продаж флагманского внед...,Фото: Tank В России стартовали продажи рамного...,['\n Новости\n ...,None
5,5,NaN,NaN,"Букингемский дворец подтвердил, что принц Гарр...",[],None
6,6,https://rbclife.ru/news/6436be7a9a79470c183f41...,NaN,NaN,[],None
7,7,NaN,NaN,Xiaomi 13 Ultra появился на первых рендерах за...,[],None
8,8,https://rbclife.ru/news/643673f69a79479b6dc63e...,NaN,NaN,[],None
9,9,NaN,NaN,Писательница из Санкт-Петербурга Дарина Мишина...,[],None
10,10,https://rbclife.ru/news/643676469a79479c09354d...,NaN,NaN,[],None
11,11,NaN,NaN,Исполнитель главной роли в сериале The Last of...,[],None
12,12,https://rbclife.ru/news/643675f79a79479c64b38b...,NaN,NaN,[],None
13,13,NaN,NaN,"Разбираемся, что помогает терять вес и как пох...",[],None
14,14,https://rbclife.ru/news/642ffaa79a794735f49dae...,NaN,NaN,[],None
15,15,NaN,NaN,"«МегаФон», один из крупнейших сотовых оператор...",[],None
16,16,https://www.rbc.ru/technology_and_media/12/04/...,«МегаФон» попал в санкционный список США. Что ...,"«МегаФон», один из крупнейших сотовых оператор...","['МегаФон', 'операторы', 'санкции', 'Алишер Ус...",2023-04-12 00:00:00
17,17,NaN,NaN,Гендиректор «Роскосмоса» Борисов: Путин одобри...,[],None
18,18,https://www.rbc.ru/rbcfreenews/643703b99a79472...,"Борисов заявил, что Путин одобрил создание Рос...",Юрий Борисов (Фото: Сергей Савостьянов / ТАСС)...,"['Юрий Борисов', 'Роскосмос', 'орбитальная ста...",None
19,19,NaN,NaN,Всемирный банк выделил грант в размере $200 мл...,[],None

In [57]:
rbc = preprocess(df)
rbc

C:\Users\Egor Kolyuzhnov\AppData\Local\Temp\ipykernel_18428\540580304.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'].iloc[i] = df['Date'].iloc[i - 1]
C:\Users\Egor Kolyuzhnov\AppData\Local\Temp\ipykernel_18428\1043547710.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Text'].iloc[i] = stemming(df['Text'].iloc[i])

,Unnamed: 0,URL,Date,Text
16,16,https://www.rbc.ru/technology_and_media/12/04/...,2023-04-12,«мегафон» попа санкцион список сша эт знач «ме...
18,18,https://www.rbc.ru/rbcfreenews/643703b99a79472...,2023-04-12,борис заяв путин одобр создан российск орбитал...
20,20,https://www.rbc.ru/rbcfreenews/6436e71a9a79472...,2023-04-12,всемирн банк выдел украин млн восстановлен инф...
22,22,https://www.rbc.ru/rbcfreenews/6436fbdd9a79472...,2023-04-12,hbo показа перв тизер сериа «гарр поттеру» стр...
24,24,https://www.rbc.ru/technology_and_media/12/04/...,2023-04-12,уорр баффетт рассказа билл гейтс помог ем chat...
...,...,...,...,...
135236,135236,http://top.rbc.ru/politics/21/01/2015/54bf999b...,2015-01-21,войн слов год измен риторик путин обам президе...
135238,135238,http://top.rbc.ru/business/21/01/2015/54bfe191...,2015-01-21,владимир якунин соглас раскр сво доход президе...
135240,135240,http://top.rbc.ru/technology_and_media/21/01/2...,2015-01-21,apple запрет продава сво техник крым apple раз...
135242,135242,http://top.rbc.ru/technology_and_media/21/01/2...,2015-01-21,pussy riot попадут обложк британск wired англи...
135244,135244,http://www.rbc.ru/rbcfreenews/54bfb70c9a794765...,2015-01-21,путин наград медал сын игор сечин президент вл...

In [61]:
#rbc = rbc.drop(columns=['URL'])
df = pd.concat([interfax, ria, rbc])
df = df.sort_values('Date', ascending=False)
df = df[df['Date'] >= datetime.datetime(2015, 1, 1)]
for i in range(df.shape[0]):
    date = df['Date'].iloc[i]
    df['Date'].iloc[i] = datetime.datetime(date.year, date.month, date.day)
df

,Unnamed: 0,Date,Text
168,168,2023-04-12 00:00:00,«ментовск войны» обошл приквел «игр престолов»...
128,128,2023-04-12 00:00:00,рпц назва «странной» возможн пасхальн перемир ...
174,174,2023-04-12 00:00:00,«велик отказ» компан росс теря деньг массов фе...
172,172,2023-04-12 00:00:00,набиуллин увидел повод влиян курс рубл цб выст...
170,170,2023-04-12 00:00:00,британ ввел санкц прот usm усманов член сем ке...
...,...,...,...
81842,81842,2015-01-01 14:44:00,cудмедэксперт приступ осмотр тел жертв крушен ...
81843,81843,2015-01-01 13:28:00,кадыр сообщ уничтожен главар бандгрупп мус зав...
81846,81846,2015-01-01 10:37:00,роспотребнадзор призва россия перееда напива п...
81845,81845,2015-01-01 10:26:00,российск спасател присоедин поиск малайзийск с...
81844,81844,2015-01-01 10:18:00,ряд регион центральн росс отмен электричк объе...

In [236]:
import datetime
words = [
    "газпром",
    "газ",
    "нефть",
    "бензин",
    "санкции",
    "кризис",
    "рубль",
    "рост",
    "падение",
    "цена",
    "подорожание",
    "удешевение"
]
_filter = df['Text'].str.contains(" " + stemming(words[0]) + " ")
for w in words:
    s = stemming(w)
    _filter |= df['Text'].str.contains(" " + s + " ")
    _filter |= df['Text'].str.contains("^" + s + " ")
    _filter |= df['Text'].str.contains(" " + s + "$")
filtered = df[_filter]

KeyboardInterrupt:

In [243]:
before_start = filtered[filtered['Date'] >= datetime.datetime(2015, 1, 1)]
for i in range(before_start.shape[0]):
    date = before_start['Date'].iloc[i]
    before_start['Date'].iloc[i] = datetime.datetime(date.year, date.month, date.day)
before_start.describe(include="all", datetime_is_numeric=True)
before_start

C:\Users\Egor Kolyuzhnov\AppData\Local\Temp\ipykernel_58308\365184396.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  before_start['Date'].iloc[i] = datetime.datetime(date.year, date.month, date.day)

,Unnamed: 0,Date,Text
3,3,2023-04-09,полиц ира будет отслежива ношен хиджаб помощ к...
8,8,2023-04-09,три ракет был выпущ сир сторон голанск высот а...
10,10,2023-04-08,произошл ден суббот апрел ракет крым учен тайв...
13,13,2023-04-08,сотрудник tesla год пересыла друг друг виде ка...
14,14,2023-04-08,twitch wikimedia гроз миллион штраф неудален з...
...,...,...,...
81823,81823,2015-01-05,президент франц заяв возможн отм санкц отношен...
81824,81824,2015-01-05,правительств продолж субсидирова региональн ав...
81828,81828,2015-01-04,итог главн пользовател осваива интернет рост р...
81832,81832,2015-01-04,правительств росс обнов перечен жизнен важн ле...
81837,81837,2015-01-03,итог сам сложн год туризм минувш год стал тури...

In [334]:
funds = pd.read_excel("./gazprom-moscow-exchange.xlsx")
funds['Дата'] = pd.to_datetime(funds['Дата'], dayfirst=True)
funds['Change'] = 0
funds = funds.sort_values("Дата")
for i in range(1, funds.shape[0]):
    funds['Change'].iloc[i] = funds['Цена avg'].iloc[i] - funds['Цена avg'].iloc[i - 1]
funds.tail(10)

C:\Users\Egor Kolyuzhnov\AppData\Local\Temp\ipykernel_58308\4236339736.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  funds['Change'].iloc[i] = funds['Цена avg'].iloc[i] - funds['Цена avg'].iloc[i - 1]

,Дата,Bid,Ask,Цена open,Цена min,Цена max,Цена last,Цена avg,Оборот,Кол-во сделок,Change
9,2023-03-28,171.02,171.08,172.94,169.10,172.94,171.07,170.58,4614333299,74028,-1.24
8,2023-03-29,170.91,170.96,171.58,169.41,172.50,170.95,171.13,3841502396,59297,0.55
7,2023-03-30,171.71,171.72,170.78,170.02,171.80,171.71,171.13,2517969423,41954,0.00
6,2023-03-31,169.83,169.85,172.00,168.14,172.71,169.83,169.90,5331859695,89990,-1.23
5,2023-04-03,170.30,170.34,170.99,169.00,171.50,170.38,170.24,3879998447,68103,0.34
4,2023-04-04,172.54,172.55,171.00,170.14,176.00,172.55,173.81,12722343198,149732,3.57
3,2023-04-05,173.86,173.87,172.55,170.58,174.48,173.86,172.95,5691178694,68565,-0.86
2,2023-04-06,171.52,171.56,174.02,171.30,175.00,171.60,173.34,5244430462,78986,0.39
1,2023-04-07,173.07,173.09,171.50,171.29,173.18,173.09,172.30,3089494250,54104,-1.04
0,2023-04-10,174.54,174.55,173.55,173.23,175.20,174.54,174.18,4070633698,64768,1.88

In [327]:
changes = {}
for i in range(1, funds.shape[0]):
    start = funds["Дата"].iloc[i - 1]
    end = funds["Дата"].iloc[i]
    date = start
    while date < end:
        changes[str(date)] = funds['Change'].iloc[i]
        date += datetime.timedelta(days=1)

In [332]:
before_start['Change'] = 0
for i in range(before_start.shape[0]):
    date = before_start["Date"].iloc[i]
    if str(date) in changes:
        change = changes[str(date)]
        before_start["Change"].iloc[i] = change
before_start.head(10)

C:\Users\Egor Kolyuzhnov\AppData\Local\Temp\ipykernel_58308\916556137.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  before_start['Change'] = 0
C:\Users\Egor Kolyuzhnov\AppData\Local\Temp\ipykernel_58308\916556137.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  before_start["Change"].iloc[i] = change

,Unnamed: 0,Date,Text,Change
3,3,2023-04-09,полиц ира будет отслежива ношен хиджаб помощ к...,1.88
8,8,2023-04-09,три ракет был выпущ сир сторон голанск высот а...,1.88
10,10,2023-04-08,произошл ден суббот апрел ракет крым учен тайв...,1.88
13,13,2023-04-08,сотрудник tesla год пересыла друг друг виде ка...,1.88
14,14,2023-04-08,twitch wikimedia гроз миллион штраф неудален з...,1.88
15,15,2023-04-08,большинств россия увидел дефицит нужн иностра ...,1.88
19,19,2023-04-08,лавр возглав делегац росс конференц стран сосе...,1.88
22,22,2023-04-07,произошл ден пятниц апрел нов рекорд курс валю...,1.88
23,23,2023-04-07,минторг сша рассматрива введен мер отношен про...,1.88
24,24,2023-04-07,рубл заверш торг пятниц небольш повышен доллар...,1.88

In [329]:
for i in range(before_start.shape[0]):
    before_start['Change'].iloc[i] = "INCREASE" if before_start['Change'].iloc[i] > 0 else "DECREASE"
before_start

C:\Users\Egor Kolyuzhnov\AppData\Local\Temp\ipykernel_58308\2587082583.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  before_start['Change'].iloc[i] = "INCREASE" if before_start['Change'].iloc[i] > 0 else "DECREASE"

,Unnamed: 0,Date,Text,Change
3,3,2023-04-09,полиц ира будет отслежива ношен хиджаб помощ к...,INCREASE
8,8,2023-04-09,три ракет был выпущ сир сторон голанск высот а...,INCREASE
10,10,2023-04-08,произошл ден суббот апрел ракет крым учен тайв...,INCREASE
13,13,2023-04-08,сотрудник tesla год пересыла друг друг виде ка...,INCREASE
14,14,2023-04-08,twitch wikimedia гроз миллион штраф неудален з...,INCREASE
...,...,...,...,...
81823,81823,2015-01-05,президент франц заяв возможн отм санкц отношен...,INCREASE
81824,81824,2015-01-05,правительств продолж субсидирова региональн ав...,INCREASE
81828,81828,2015-01-04,итог главн пользовател осваива интернет рост р...,DECREASE
81832,81832,2015-01-04,правительств росс обнов перечен жизнен важн ле...,DECREASE
81837,81837,2015-01-03,итог сам сложн год туризм минувш год стал тури...,DECREASE